# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dv4aby/Code/Graphical-Sorting

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dv4aby/Code/Graphical-Sorting

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dv4aby/Code/Graphical-Sorting/CMakeFiles /Users/dv4aby/Code/Graphical-Sorting//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dv4aby/Code/Graphical-Sorting/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GraphicalSorting

# Build rule for target.
GraphicalSorting: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GraphicalSorting
.PHONY : GraphicalSorting

# fast build rule for target.
GraphicalSorting/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicalSorting.dir/build.make CMakeFiles/GraphicalSorting.dir/build
.PHONY : GraphicalSorting/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicalSorting.dir/build.make CMakeFiles/GraphicalSorting.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicalSorting.dir/build.make CMakeFiles/GraphicalSorting.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicalSorting.dir/build.make CMakeFiles/GraphicalSorting.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sorting_algorithms.o: src/sorting_algorithms.cpp.o
.PHONY : src/sorting_algorithms.o

# target to build an object file
src/sorting_algorithms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicalSorting.dir/build.make CMakeFiles/GraphicalSorting.dir/src/sorting_algorithms.cpp.o
.PHONY : src/sorting_algorithms.cpp.o

src/sorting_algorithms.i: src/sorting_algorithms.cpp.i
.PHONY : src/sorting_algorithms.i

# target to preprocess a source file
src/sorting_algorithms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicalSorting.dir/build.make CMakeFiles/GraphicalSorting.dir/src/sorting_algorithms.cpp.i
.PHONY : src/sorting_algorithms.cpp.i

src/sorting_algorithms.s: src/sorting_algorithms.cpp.s
.PHONY : src/sorting_algorithms.s

# target to generate assembly for a file
src/sorting_algorithms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicalSorting.dir/build.make CMakeFiles/GraphicalSorting.dir/src/sorting_algorithms.cpp.s
.PHONY : src/sorting_algorithms.cpp.s

src/ui.o: src/ui.cpp.o
.PHONY : src/ui.o

# target to build an object file
src/ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicalSorting.dir/build.make CMakeFiles/GraphicalSorting.dir/src/ui.cpp.o
.PHONY : src/ui.cpp.o

src/ui.i: src/ui.cpp.i
.PHONY : src/ui.i

# target to preprocess a source file
src/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicalSorting.dir/build.make CMakeFiles/GraphicalSorting.dir/src/ui.cpp.i
.PHONY : src/ui.cpp.i

src/ui.s: src/ui.cpp.s
.PHONY : src/ui.s

# target to generate assembly for a file
src/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicalSorting.dir/build.make CMakeFiles/GraphicalSorting.dir/src/ui.cpp.s
.PHONY : src/ui.cpp.s

src/visualization.o: src/visualization.cpp.o
.PHONY : src/visualization.o

# target to build an object file
src/visualization.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicalSorting.dir/build.make CMakeFiles/GraphicalSorting.dir/src/visualization.cpp.o
.PHONY : src/visualization.cpp.o

src/visualization.i: src/visualization.cpp.i
.PHONY : src/visualization.i

# target to preprocess a source file
src/visualization.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicalSorting.dir/build.make CMakeFiles/GraphicalSorting.dir/src/visualization.cpp.i
.PHONY : src/visualization.cpp.i

src/visualization.s: src/visualization.cpp.s
.PHONY : src/visualization.s

# target to generate assembly for a file
src/visualization.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphicalSorting.dir/build.make CMakeFiles/GraphicalSorting.dir/src/visualization.cpp.s
.PHONY : src/visualization.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... GraphicalSorting"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sorting_algorithms.o"
	@echo "... src/sorting_algorithms.i"
	@echo "... src/sorting_algorithms.s"
	@echo "... src/ui.o"
	@echo "... src/ui.i"
	@echo "... src/ui.s"
	@echo "... src/visualization.o"
	@echo "... src/visualization.i"
	@echo "... src/visualization.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

